# Reference: https://rust-lang.github.io/rustfmt/

style_edition     = "2024"
unstable_features = true

max_width                    = 100
tab_spaces                   = 4
hard_tabs                    = false
blank_lines_upper_bound      = 1
wrap_comments                = false
condense_wildcard_suffixes   = true
enum_discrim_align_threshold = 40
struct_field_align_threshold = 40
format_macro_matchers        = true
use_field_init_shorthand     = false
format_code_in_doc_comments  = true
format_strings               = true
where_single_line            = false
imports_indent               = "Visual"
imports_layout               = "HorizontalVertical"
combine_control_expr         = false
fn_params_layout             = "Tall"
match_block_trailing_comma   = false
normalize_comments           = true
normalize_doc_attributes     = true
overflow_delimited_expr      = true
reorder_impl_items           = false
control_brace_style          = "ClosingNextLine"
use_try_shorthand            = true
format_macro_bodies          = true
brace_style                  = "SameLineWhere"
group_imports                = "Preserve"
imports_granularity          = "Module"


use_small_heuristics           = "Default"
fn_call_width                  = 80
attr_fn_like_width             = 80
struct_lit_width               = 25
struct_variant_width           = 50
array_width                    = 60
chain_width                    = 60
single_line_if_else_max_width  = 70
single_line_let_else_max_width = 70
