[env]
RUST_LOG = "debug"


[alias]
# base
s = "size"

# release
br = "build --release"
rr = "run --release"
sr = "size --release"


# default_dev feature
bd = "build --no-default-features --features default-dev"
rd = "run --no-default-features --features default-dev"
sd = "size --no-default-features --features default-dev"

brd = "br --no-default-features --features default-dev"
rrd = "rr --no-default-features --features default-dev"
srd = "sr --no-default-features --features default-dev"


# exaples
ex1 = "run --example 01"
ex2 = "run --example 02"
ex3 = "run --example 03"
ex4 = "run --example 04"
ex5 = "run --example 05"
